### ISSUE TITLE
הטנק מקולקל

### ISSUE THREAD

**Issue by erelsgl** [Game-Dev-RDA/IsraelWarsEx7#1]
אני לוחץ על החיצים, אבל הטנק לא זז אלא מסתובב במקום... גם הקנה שלו לא יורה קדימה אלא הצידה. וגם כשבסוף הצלחתי לפגוע, לא קרה כלום. זה בכוונה? אם כן, אז צריך להגיד "מלחמת יום כיפור - אתה צריך לנצח את כל הטנקים הסוריים עם טנק אחד מקולקל"

**Comment by Reut212** [comment]
התנועה של הטנק היא כמו תנועה של נהיגה ברכב. חץ למעלה = גז. חץ למטה = רוורס והחצים ימינה-שמאלה משמשים לניתוב הטנק ימינה ושמאלה. כמו בנהיגה ברכב לחיצה על החצים צריכה להתבצע במקביל.

**Comment by Reut212** [comment]
תזוזת הקנה מתבצעת על פי העכבר. כאשר מכוונים את העכבר לטנק אויב הקנה זז לעבר הטנק וניתן לירות עליו על ידי לחיצה בעכבר.

**Comment by erelsgl** [comment]
אה, הבנתי. כדאי לכתוב את זה בצד, כי זה מאד שונה מהתנועה המקובלת במשחקים.

**Comment by Reut212** [comment]
תודה על הארה. הוספתי את זה לתדריך של המשימה.
